apiVersion: apps/v1
kind: Deployment
metadata:
  name: beikeshop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beikeshop-api
  template:
    metadata:
      labels:
        app: beikeshop-api
    spec:
      containers:
      - name: beikeshop-api
        image: hishammpsn/beikeshop_api:1.5.1
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: beikeshop-api-service
spec:
  selector:
     app: beikeshop-api 
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 4000   
      nodePort: 31000    
  type: NodePort        

