name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Debug: Ensure correct folder structure
    - name: Debug folder structure
      run: ls -la /home/ubuntu/actions-runner-backend/_work/beikeshoplatest/beikeshoplatest

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies in server folder
    - name: Install dependencies
      run: npm ci
      working-directory: /home/ubuntu/actions-runner-backend/_work/beikeshoplatest/beikeshoplatest/server

    # Set up environment variables
    - name: Set up environment variables
      run: |
        touch /home/ubuntu/actions-runner-backend/_work/beikeshoplatest/beikeshoplates/server/.env
        echo "${{ secrets.PROD_ENV_FILE }}" > /home/ubuntu/actions-runner-backend/_work/beikeshoplatest/beikeshoplatest/server/.env

    # Run tests
    - name: Run tests
      run: npm test
      working-directory: /home/ubuntu/actions-runner-backend/_work/beikeshoplatest/beikeshoplatest/server



