name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Debug: List files in the server folder
    - name: Debug server folder
      run: ls -la ./server

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm ci
      working-directory: ./server

    # Set up environment variables
    - name: Set up environment variables
      run: |
        touch ./server/.env
        echo "${{ secrets.PROD_ENV_FILE }}" > ./server/.env

    # Run tests
    - name: Run tests
      run: npm test
      working-directory: ./server



