# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Navigate to the server folder and install dependencies
    - name: Install dependencies
      run: npm ci
      working-directory: ./server

    # Create and configure the .env file
    - name: Set up environment variables
      run: |
        touch ./server/.env
        echo "${{ secrets.PROD_ENV_FILE }}" > ./server/.env

    # Run tests (optional, remove if not needed)


