name: Deploy to EC2

on:
  push:
    branches:
      - master  # Make sure this matches your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on GitHub-hosted Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies for the server
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # # Step 4: Deploy to EC2
      # - name: Deploy to EC2
      #   env:
      #     EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  # Private key stored in GitHub Secrets
      #     EC2_HOST: ${{ secrets.EC2_HOST }}  # EC2 public IP stored in GitHub Secrets
      #     EC2_USER: ${{ secrets.EC2_USER }}  # EC2 user stored in GitHub Secrets
      #   run: |
      #     # Convert the private key to the correct format and use it for SSH
      #     echo "$EC2_PRIVATE_KEY" > private_key.pem
      #     chmod 400 private_key.pem

      #     # SSH into the EC2 instance and deploy the application
      #     ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
      #       cd /path/to/your/project  # Navigate to your project directory on the EC2 instance
      #       git pull origin main  # Pull the latest code from the repository
      #       npm install  # Install any new dependencies
      #       pm2 restart app  # Restart the application using PM2 (or use your process manager)
      #     EOF

      # Optional: Clean up the private key file after deployment
      # - name: Clean up private key
      #   run: rm private_key.pem
